# Generated by Django 5.0 on 2023-12-23 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
